In [1]:
import numpy as np
import load_files 
import logistic_regression

/Users/ianbenlolo/Desktop/Mcgill/comp_551/ML-Project1/src/logistic_regression.py:56: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(n == y.shape[0], "the data and output array shapes are not equal")


In [2]:
wine,wine_headers = load_files.load_wine()
cancer,cancer_headers = load_files.load_cancer()

In [3]:
X = wine[:,:-1]
y = wine[:,-1]
X.shape

(1599, 11)

In [7]:
np.insert(np.copy(X), 0, 1, axis=1)

array([[1.        , 0.24778761, 0.39726027, ..., 0.60629921, 0.13772455,
        0.15384615],
       [1.        , 0.28318584, 0.52054795, ..., 0.36220472, 0.20958084,
        0.21538462],
       [1.        , 0.28318584, 0.43835616, ..., 0.40944882, 0.19161677,
        0.21538462],
       ...,
       [1.        , 0.15044248, 0.26712329, ..., 0.53543307, 0.25149701,
        0.4       ],
       [1.        , 0.11504425, 0.35958904, ..., 0.65354331, 0.22754491,
        0.27692308],
       [1.        , 0.12389381, 0.13013699, ..., 0.51181102, 0.19760479,
        0.4       ]])

In [107]:

print(normalize(X[:,:-1]).shape, X[:,-1].shape)

X[:,:-1] = normalize(np.copy(X[:,:-1]))

final = np.zeros((X.shape[0], X.shape[1] + 1))
# np.vstack((normalize(X[:,:-1]),X[:,-1] ))


(1599, 10) (1599,)


ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [108]:
final.shape

(1599, 12)

In [5]:
model = logistic_regression.Logistic(X.shape[1])

In [6]:
model.fit(X,y,100)

TypeError: sigmoid() takes 1 positional argument but 2 were given

In [104]:
def normalize(arr,axis = 0): 
    """ 
    normalize (put in range [0,1]) ane array along an axis

    """
    min = arr.min(axis=axis) 
    minus_arr = arr.T - min[:,np.newaxis]

    norm_arr = minus_arr / minus_arr.T.max(axis =axis)[:,np.newaxis]
    return norm_arr.T

In [84]:


x =np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14]).reshape((7,2))
#x = np.asarray([[1,2,3],[4,5,6],[7,8,9,10,11,12]])
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [85]:
row_min = x.min(axis=0)
new_matrix = x.T - row_min[:,np.newaxis]
new_matrix2 = new_matrix / new_matrix.T.max(axis =0)[:,np.newaxis]

In [86]:
print(row_min)
new_matrix


[1 2]


array([[ 0,  2,  4,  6,  8, 10, 12],
       [ 0,  2,  4,  6,  8, 10, 12]])

In [87]:
new_matrix2

array([[0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
        0.83333333, 1.        ],
       [0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
        0.83333333, 1.        ]])